version: "3.4"

services:
  dev:
    build:
      context: .
      target: DEV
    volumes:
      - .:/app/
      - ~/.aws/credentials:/root/.aws/credentials:ro

  docs:
    build:
      context: .
      target: DOCS
    volumes:
      - .:/app/

  release:
    build:
      context: .
      target: RELEASE
    volumes:
      - .:/app/
      - ~/.gitconfig:/root/.gitconfig
